apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ssm-secured 
  janus-idp.io/tekton: ssm-secured
  backstage.io/kubernetes-id: ssm-secured
  backstage.io/kubernetes-namespace: rhtap-ssm 
  app.kubernetes.io/part-of: ssm-secured
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml