apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ssm-secured-gitops
  description: This is GitOps manifest for ssm-secured   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=ssm-secured
    backstage.io/kubernetes-id: ssm-secured 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ssm-secured   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ssm-secured
